---

- name: jenkins-configure | Enable Jenkins security
  template: src=config.xml.j2 dest={{jenkins_home}}/config.xml
            owner=jenkins group=jenkins

- name: jenkins-configure | Deploy QueueItemAuthenticator configuration
  copy: src=jenkins.security.QueueItemAuthenticatorConfiguration.xml
        dest={{jenkins_home}}/jenkins.security.QueueItemAuthenticatorConfiguration.xml
        owner=jenkins group=jenkins

- name: jenkins-configure | Set up Jenkins admin user dir
  file: path={{jenkins_home}}/users/{{jenkins_admin_user}} state=directory
        owner=jenkins group=jenkins

- name: jenkins-configure | Set up Jenkins admin user config
  template: src=admin_user.xml.j2 dest={{jenkins_home}}/users/{{jenkins_admin_user}}/config.xml
            owner=jenkins group=jenkins

- name: jenkins-configure | Configure Jenkins service
  template: src=jenkins.j2 dest={{jenkins_configuration}}
  register: jenkins_configure

- name: jenkins-configure | Ensure Jenkins restarted
  service: name=jenkins state=restarted
  when: jenkins_configure.changed

- name: jenkins-configure | Wait for Jenkins to open the HTTP port
  wait_for: port={{jenkins_http_port}}

- name: jenkins-configure | Copy jenkins-cli
  get_url: url=http://localhost:{{jenkins_http_port}}/jnlpJars/jenkins-cli.jar dest={{jenkins_home}}/jenkins-cli.jar
  register: jenkins_cli
  until: "'OK' in jenkins_cli.msg or 'file already exists' in jenkins_cli.msg"
  retries: 20
  delay: 5
