---

- include: install.deb.yml
  when: ansible_os_family == 'Debian'
  tags: [jenkins, jenkins-install]

- include: configure.yml
  tags: [jenkins, jenkins-configure]

- include: plugins.yml
  when: jenkins_plugins
  tags: [jenkins, jenkins-plugins]

- include: ssh.yml
  when: jenkins_ssh_key_file != ""
  tags: [jenkins, jenkins-ssh]

- include: jobs.yml
  when: jenkins_jobs
  tags: [jenkins, jenkins-jobs]

- include: nginx.yml
  when: jenkins_nginx_proxy
  tags: [jenkins, jenkins-nginx]
