---
# file: ciservers.yml
- hosts: ciservers
  remote_user: root

  vars_files:
    - vars/secrets.yml

  vars:
      jenkins_nginx_proxy: yes
      jenkins_nginx_hostname: ci.snowflake.nu
      jenkins_ssh_key_file: "/priv/jenkins.key"
      jenkins_ssh_known_hosts:
        - bitbucket.org
        - github.com
      jenkins_plugins:
        - git
        - shiningpanda
        - xvfb

  pre_tasks:
    - name: create /priv directory
      file: path=/priv state=directory mode=0700
    - name: deploy SSH key
      copy: 'content="{{ jenkins_private_key }}"
             dest=/priv/jenkins.key
             mode=0600'

  roles:
    - nginx
    - jenkins

  post_tasks:
    - name: disable NGINX default site
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify: restart nginx

    - name: install additional requirements
      apt: name={{ item }} state=present
      with_items: ["git", "firefox", "python3", "python-virtualenv", "xvfb"]

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
