---
# file: ciservers.yml
- hosts: ciservers
  remote_user: root

  vars_files:
    - vars/secrets.yml

  vars:
      jenkins_nginx_proxy: yes
      jenkins_nginx_hostname: ci.snowflake.nu
      jenkins_ssh_key_file: "/priv/jenkins.key"
      jenkins_ssh_known_hosts:
        - bitbucket.org
        - github.com
      jenkins_plugins:
        - git
        - shiningpanda
        - xvfb
      shiningpanda_pythons:
        - { name: 'System-CPython-2.7', home: '/usr/bin/python2.7' }
        - { name: 'Python-3', home: '/usr/bin/python3' }

  pre_tasks:
    - name: upgrade packages
      apt: upgrade=yes update_cache=yes
    - name: create /priv directory
      file: path=/priv state=directory mode=0700
    - name: deploy SSH key
      copy: 'content="{{ jenkins_private_key }}"
             dest=/priv/jenkins.key
             mode=0600'

  roles:
    - nginx
    - jenkins

  post_tasks:
    - name: disable NGINX default site
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify: restart nginx

    - name: install custom Jenkins requirements
      apt: name={{ item }} state=present
      with_items: ["git", "firefox", "python3", "python-virtualenv", "xvfb"]

    - name: configure ShiningPanda python installations
      template: src=shiningpanda_pythons.xml.j2
                dest={{ jenkins_home }}/jenkins.plugins.shiningpanda.tools.PythonInstallation.xml
                owner=jenkins group=jenkins
      notify:
        - restart jenkins

    - name: configure Xvfb installations
      template: src=xvfb_config.xml.j2
                dest={{ jenkins_home }}/org.jenkinsci.plugins.xvfb.XvfbBuildWrapper.xml
                owner=jenkins group=jenkins
      notify:
        - restart jenkins

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart jenkins
      service: name=jenkins state=restarted
