---
# file: roles/web/tasks/main.yml
- name: Create user account
  user: name={{ deployment_user }}

- name: Install local SSH key into authorized_keys
  authorized_key: 'user={{ deployment_user }}
                   key="{{ lookup(''file'', ''~/.ssh/id_rsa.pub'') }}"'

- name: Install system-wide OS packages
  apt: name={{ item }} state=present
  with_items:
    - nginx
    - git
    - python3
    - python3-pip

- name: Install system-wide Python packages
  pip: name=virtualenv state=present executable=pip3

- name: Disable NGINX default site
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Deploy NGINX configuration
  template: src=nginx.conf.j2
            dest=/etc/nginx/nginx.conf
            owner=root mode=0644
  notify:
    - restart nginx

- name: Enable NGINX
  service: name=nginx enabled=yes
